<?php
return array (
  'gsm3u8' => 
  array (
    'status' => '1',
    'from' => 'gsm3u8',
    'show' => 'gsm3u8',
    'des' => '有问题请联系 http://guangsuzy.com',
    'target' => '_self',
    'ps' => '1',
    'parse' => 'https://www.guangsujx.com/m3u8/?url=',
    'sort' => '9999',
    'tip' => '',
    'id' => 'gsm3u8',
  ),
  'hnm3u8' => 
  array (
    'status' => '1',
    'from' => 'hnm3u8',
    'show' => 'hnm3u8',
    'des' => '红牛m3u8纯净解析接口hongniuzy.com',
    'target' => '_self',
    'ps' => '1',
    'parse' => 'https://www.hnjiexi.com/m3u8/?url=',
    'sort' => '9999',
    'tip' => '',
    'id' => 'hnm3u8',
  ),
  'aosika' => 
  array (
    'status' => '1',
    'from' => 'aosika',
    'show' => 'aosika',
    'des' => '',
    'target' => '_self',
    'ps' => '1',
    'parse' => 'https://aosikazyplayurl.com/?url=',
    'sort' => '9988',
    'tip' => '',
    'id' => 'aosika',
  ),
  'dplayer' => 
  array (
    'status' => '1',
    'from' => 'dplayer',
    'show' => 'DPlayer-H5播放器',
    'des' => 'dplayer.js.org',
    'target' => '_self',
    'ps' => '0',
    'parse' => '',
    'sort' => '908',
    'tip' => '无需安装任何插件',
    'id' => 'dplayer',
  ),
  'videojs' => 
  array (
    'status' => '1',
    'sort' => '907',
    'from' => 'videojs',
    'show' => 'videojs-H5播放器',
    'des' => 'videojs.com',
    'parse' => '',
    'ps' => '0',
    'tip' => '无需安装任何插件',
    'id' => 'videojs',
  ),
  'iva' => 
  array (
    'status' => '1',
    'from' => 'iva',
    'show' => 'iva-H5播放器',
    'des' => 'videojj.com',
    'target' => '_self',
    'ps' => '0',
    'parse' => '',
    'sort' => '906',
    'tip' => '无需安装任何插件',
    'id' => 'iva',
  ),
  'iframe' => 
  array (
    'status' => '1',
    'from' => 'iframe',
    'show' => 'iframe外链数据',
    'des' => 'iframe外链数据',
    'ps' => '0',
    'parse' => '',
    'sort' => '905',
    'tip' => '无需安装任何插件',
    'id' => 'iframe',
  ),
  'link' => 
  array (
    'status' => '1',
    'sort' => '904',
    'from' => 'link',
    'show' => '外链数据',
    'des' => '外部网站播放链接',
    'ps' => '0',
    'parse' => '',
    'tip' => '无需安装任何插件',
    'id' => 'link',
  ),
  'swf' => 
  array (
    'status' => '1',
    'sort' => '903',
    'from' => 'swf',
    'show' => 'Flash文件',
    'des' => 'swf',
    'parse' => '',
    'ps' => '0',
    'tip' => '无需安装任何插件',
    'id' => 'swf',
  ),
  'flv' => 
  array (
    'status' => '1',
    'from' => 'flv',
    'show' => 'Flv文件',
    'des' => 'flv',
    'target' => '_self',
    'ps' => '0',
    'parse' => '',
    'sort' => '902',
    'tip' => '无需安装任何插件	',
    'id' => 'flv',
  ),
  'hnyun' => 
  array (
    'status' => '1',
    'from' => 'hnyun',
    'show' => 'hnyun',
    'des' => '',
    'target' => '_self',
    'ps' => '0',
    'parse' => '',
    'sort' => '103',
    'tip' => '',
    'id' => 'hnyun',
  ),
  'wjyun' => 
  array (
    'status' => '1',
    'from' => 'wjyun',
    'show' => 'wjyun',
    'des' => '',
    'target' => '_self',
    'ps' => '0',
    'parse' => '',
    'sort' => '2',
    'tip' => '',
    'id' => 'wjyun',
  ),
  'gsyun' => 
  array (
    'status' => '1',
    'from' => 'gsyun',
    'show' => 'gsyun',
    'des' => '',
    'target' => '_self',
    'ps' => '0',
    'parse' => '',
    'sort' => '1',
    'tip' => '',
    'id' => 'gsyun',
  ),
  'wjm3u8' => 
  array (
    'status' => '1',
    'from' => 'wjm3u8',
    'show' => 'wjm3u8',
    'des' => '',
    'target' => '_self',
    'ps' => '1',
    'parse' => 'https://jx.wujinkk.com/dplayer/?url=',
    'sort' => '1',
    'tip' => '',
    'id' => 'wjm3u8',
  ),
  'snm3u8' => 
  array (
    'status' => '1',
    'from' => 'snm3u8',
    'show' => 'snm3u8',
    'des' => '',
    'target' => '_self',
    'ps' => '1',
    'parse' => 'https://www.snplayer.com/?url=',
    'sort' => '1',
    'tip' => '',
    'id' => 'snm3u8',
  ),
  'bfzym3u8' => 
  array (
    'status' => '1',
    'from' => 'bfzym3u8',
    'show' => '暴风资源',
    'des' => '暴风资源站官网: bfzy.tv',
    'target' => '_self',
    'ps' => '1',
    'parse' => 'https://jxbfbf.com/?url=',
    'sort' => '9999',
    'tip' => '无需安装任何插件',
    'id' => 'bfzym3u8',
  ),
);